name: news_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  provider: ^6.1.2
  webview_flutter: ^3.0.1
  # webview_flutter_android: ^3.16.7
  # webview_flutter_wkwebview: ^3..0

flutter_launcher_icons:
  image_path: 'assets/images/newsLogo.png'
  android: true
  ios: true
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
